### PR TITLE
Add minify option to string output loader

### LINKED ISSUE #11: [feature request] add minify option for string output
I currently do this in runtime code before sending the request over the wire.  Would be nice to do it at the loader level, to minify graphql whitespace from the bundle:

```js
function minifyQuery(query) {
  return query
      .replace(/#.*/gm, '') // comments
      .replace(/\s\s+/g, ' ') // consecutive whitespace
      .replace(/\s*({|}|\(|\)|\.|:|,)\s*/g, '$1') // whitespace before/after operators
}
```

### PR DESCRIPTION
**Pull request by gpoitch**
Closes #11

### CODE REVIEW

**Comment by stephen** [comment]
I wonder if we should expose stripping comments as a separate option as well.

That one seems nice, but I'm less convinced that stripping whitespace/newlines is a nicer approach than gzip/compression over the wire.

**Comment by gpoitch** [comment]
Up to you and I can update.  Haven't measured the difference with whitespace/newlines and gzip - it kind of depends on what other code it's bundled with.

Besides in a browser/over-the-wire, I also use this in a node.js/serverless/lambda environment so removing whitespace helps a little with FaaS size and v8 optimizations.

**Comment by stephen** [comment]
seems reasonable. could you also update the readme to add the option and its motivations?

**Comment by stephen** [comment]
published in 0.1.2.

**Comment by gpoitch** [comment]
@stephen woah that was fast, thanks! Was fixing a minor thing but saw you merged already: https://github.com/samsarahq/graphql-loader/pull/14

**Pull request merged**
